#!/bin/bash

SERVER=$1
CERTIFICATE=/app/cert/sshdocker
NOMBRE_DE_COMMENTAIRE_LEGITIME=$2


NOMBRE_DE_COMMENTAIRE_TOTAL=$(mysql -h $SERVER -umaki -pmaki -B maki2 -e "SELECT COUNT(*) FROM commentaires;")

TAUX_DE_FAUX_COMMENTAIRE=$((($NOMBRE_DE_COMMENTAIRE_TOTAL-$NOMBRE_DE_COMMENTAIRE_LEGITIME)/$NOMBRE_DE_COMMENTAIRE_TOTAL)*100)

echo $TAUX_DE_FAUX_COMMENTAIRE | awk '{print int($1+0.5)}'